name: Download DeepSeek APK

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        run: curl -L "https://pixeldrain.com/api/file/2fhL9xeo" -o jekd.mp4
        
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: backg.mp4
          path: back.mp4
